version: '3.8'

services:
  bresort:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6778:6778'
    environment:
      - NODE_ENV=production
      - PORT=6778
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:6778/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bresort_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - bresort
    restart: unless-stopped
    networks:
      - bresort_network

networks:
  bresort_network:
    driver: bridge
